server:
  port: 7000
spring:
  application:
    name: atguigu-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.10.117
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    alipay-public-key: xxxxx
    app-id: xxxxxxxx
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: xxxxx
    notify-url: http://w428pt.natappfree.cc/pay/notify
    return-url: http://www.crowd.com/pay/return
    sign-type: RSA2
