server:
  port: 7000
spring:
  application:
    name: atguigu-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.10.117
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi9ZrA27cisfA50Kow3ppTqcu8RxvSx3aOW8rp63vLoSal3PSM42kht60dKm1Tb4dnoS4sgA9Ridb+q9rVGlYi+KNPE/lYbNr24c7sgzpM2foQGRwjks2NeC2V2eKx8z/0V8MWzbHS93q5tjHEEdAl5UHTSUHZPq8BjepzxipJzTep1UIgOogzdOgyNz2mjnBP4gFpoTOOL6ZAtfEGAfWosXN/QxHO+LO2KSutNN8SbVAzXGUkktfo3jqzQPHyJzj7N4i47+YQwy+HXqZ/qUZ13uGPxrF/c2vIU+h5TnUGnuYDE2tFYKjrXOd3U/9Ci2851OE/Ms5PuUMmOOwWJaMzQIDAQAB
    app-id: 2021000118656482
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCmJtdJ/mD1KSCIdbJR5UIr3VFzmblcT0Sv4xzmjYSYioc6IdlG5Rq8pG77YIGY3IXl379TBiUGbG5p7v+k6q+s/D/5NkLWH0xho9X1TbivL0zU8FQYPp3+ABL51xHGaj+xsCNBlCNpf0kWfkphMsbHySdT3rsHcpv9wB99ahRut5QCJBJ5s4E8HGSERcxeyHI01pAZ7xVHXouNyzeubCB13CzJiaaEpyd7kKrQaJx7ZZfCh/BBU/nK6LHIPR31zD3Cp+bXY0UL7b/DCDNQ7dxVihedaXqJKvIrknV0TbLAb1/saWKWipQvyNMYOXqU4hmN9e3MB9URA1sHLL4pGrhdAgMBAAECggEAPY2QHmpt0wUsd0FbEXnkXMm9/hyKDgeTw7FYqJTu9XAEjuWxT9FaaV5lex0SheXUeQe+ImzZVJrhAL+414jWEjjVHmcataacrmN6xUjIzaWxSgXKsbyo3Ut7vDEP9biw5gwB066ku9Wa5wlcVsvv1l3QAwM1uJmd7pC5WcXt0eH4ywrkAleJMq2Q6jvl0cse+cKaCNIsm0fQ84XQkjIqQ7EEW8f2vYfOc0PNKPbImamRGYbZ8YMiEixk+306iNUnnY4Q1rqvCVImUfNDFKtHKfr4IZCHVLKUYVs/ZQ7IrXexKA5F36gspSn9x25at/wPqlB0qHpuwgxJz3/lHTuF5QKBgQDntnCVfcYTQqlotRcgSTRFl/hdIMGPZXC6ctEtGi02/b+tFSTi8x3aRcPIe1zMUJJGFGlWliEnOFmowLWTuKplpnX07ISi37/SKbIGNAAMr3Cor4RN3xEd4QF72G4eVGxux5RtKS+2r1WjfcDDi6UIXqHLJCNQshSE8IR7pYxjowKBgQC3kTNYZ3iwtKl4IFIx1t+sIl8EuPZMj1/0RC99A5Vme0AgdkZkNousmg+6qvXCbyZAN9jTNu2SxwrU8V0Rce4D5x6XqYW9HNipbixr2eAS7Y4lCowOkblRgMcEIPAa63GISRlZMjO7oWzWyTux2vkwHgZHMRoZgw54VSpuQo4z/wKBgFzl3R9iLJ6eNFNhfyMXllhshEu6DUBTeC2YSNrfSs9oToezGXXP6OEQ5VykcOENUIe+OTlYuXQC+Jdao7HU8KQOZ+5JQSgXss0soE4yXO65C97ld5LM4wzqn/CqJgQM7ug/JffZ8mI4y4nfqf/8Ja9EWXObSnlY3DcsQsFb7vwnAoGBAKyuCJD29Q+1Q15feTKtIUe6JYw5umgWz3rm0Y1WW6pF8vMWj+0hao75diZxQDKhgGgUoQE/wIi8eLIMQzJv7Cj7t0mQDODzS9VGcL8b+6+SjI7HtyzVZHEJJS37FiMcrHY53YCMuyGcHtiGAIO0q4jaFanOxPCO2oPUCdAjB8ZdAoGBAL+ERbhP7OUmIxWuJUtdTsOuvw3RcEqbfoG9bDVAKGvsfuvxaIcB8uSuF6RC2EbpN/0QAQlG3dt6ZQwlUuS3jXaHfnYPUqJ8DBquky6S3Hy8dMIAEUMvOUCz7d6j6ibTNO/UP/hbcDJ141xPwRRGZj4liM32byBe1UIbqSESRN/L
    notify-url: http://w428pt.natappfree.cc/pay/notify
    return-url: http://www.crowd.com/pay/return
    sign-type: RSA2