server:
  port: 5000

spring:
  application:
    name: atguigu-crowd-project
  redis:
    host: 192.168.10.117
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

aliyun:
  oss:
    access-key-id: LTAI5tF8Mcm3hBbiEk2XoiHf
    access-key-secret: 0zhjmqjCrUJcPeZlhbXmcB9NDSsGbD
    bucket-domain: http://211122atcrowdfunding.oss-cn-hangzhou.aliyuncs.com
    bucket-name: 211122atcrowdfunding
    end-point: http://oss-cn-hangzhou.aliyuncs.com